version: '3.1'

services:
  zoo1:
    image: zookeeper:3.5.8
    network_mode: bridge
    restart: always
    hostname: zoo1
    extra_hosts:
      zoo1: 172.18.0.5
      zoo2: 172.18.0.6
      zoo3: 172.18.0.7
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      ck-net:
        ipv4_address: 172.18.0.5

  zoo2:
    image: zookeeper:3.5.8
    network_mode: bridge
    restart: always
    hostname: zoo2
    extra_hosts:
      zoo1: 172.18.0.5
      zoo2: 172.18.0.6
      zoo3: 172.18.0.7
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      ck-net:
        ipv4_address: 172.18.0.6

  zoo3:
    image: zookeeper:3.5.8
    network_mode: bridge
    restart: always
    hostname: zoo3
    extra_hosts:
      zoo1: 172.18.0.5
      zoo2: 172.18.0.6
      zoo3: 172.18.0.7
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      ck-net:
        ipv4_address: 172.18.0.7

networks:
  # default:
  #     external:
  #         name: bridge
  ck-net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.1/16
         gateway: 172.18.0.1